### ISSUE TITLE
Cannot intialize span: Trace is closed

### ISSUE THREAD

**Issue by simonphughes** [serverless/dashboard#322]
Just installed the console observability layer into our aws platform which has a large deployment of lambda apis. Initial impression is great as it gives us a fantastic view across the whole platform. I can see errors in there which I hadn't seen before and will provide me the ability to see when the system hits periods of high usage.

But I keep seeing this error in there which I think is related to the serverless layer rather than our codebase, as everything appears to be working correctly. 

Stack trace below
Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: Cannot intialize span: Trace is closed","reason":{"errorType":"Error","errorMessage":"Cannot intialize span: Trace is closed","code":"UNREACHABLE_TRACE","stack":["Error: Cannot intialize span: Trace is closed","

   at new TraceSpan (/opt/sls-sdk-node/index.js:2156:33)","
   at Object.serverlessSdk.createTraceSpan (/opt/sls-sdk-node/index.js:3242:61)","
   at request2 (/opt/sls-sdk-node/index.js:2525:41)","
   at /var/task/node_modules/node-fetch/lib/index.js:1438:15","
   at new Promise (<anonymous>)","
   at fetch (/var/task/node_modules/node-fetch/lib/index.js:1407:9)","
   at fetch (/var/task/node_modules/cross-fetch/dist/node-ponyfill.js:10:20)","
   at GraphQLClient.<anonymous> (/var/task/node_modules/graphql-request/src/index.ts:87:28)","
   at step (/var/task/node_modules/graphql-request/dist/index.js:63:23)","
   at Object.next (/var/task/node_modules/graphql-request/dist/index.js:44:53)","
   at /var/task/node_modules/graphql-request/dist/index.js:38:71","
   at new Promise (<anonymous>)","
   at __awaiter (/var/task/node_modules/graphql-request/dist/index.js:34:12)","
   at GraphQLClient.request (/var/task/node_modules/graphql-request/dist/index.js:151:16)","
   at h (/var/task/src/controllers/mypath/mycode.ts:600:31)","
   at Timeout._onTimeout (/var/task/src/controllers/mypath/mycode.ts:249:17)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: Cannot intialize span: Trace is closed","
   at process.<anonymous> (/var/runtime/index.js:35:15)","
   at process.emit (events.js:400:28)","
   at process.emit (/var/task/node_modules/source-map-support/source-map-support.js:495:21)","
   at processPromiseRejections (internal/process/promises.js:245:33)","
   at processTicksAndRejections (internal/process/task_queues.js:96:32)"]}

Any thoughts on what is causing this, or how to resolve. Thanks.

**Comment by simonphughes** [comment]
Sometimes also see the following which could be related. 

Serverless SDK Warning: Following trace spans didn't end before end of lambda invocation: node.https.request, node.https.request, node.https.request, node.https.request, node.https.request, node.https.request, node.https.request, node.https.request, node.https.request

**Comment by medikoo** [comment]
@simonphughes Great thanks for reporting that.

Can you share a bit more about a scenario in which you get this error? Is this possible for you to prepare a reproduction case we can test on our side?

**Comment by simonphughes** [comment]
I will have a think about it and see what I can do, although its very sporadic. Its only happening in 2 functions out of about 20. And in the last hour we have had 1500 invocations and its happened in 40.

**Comment by medikoo** [comment]
@simonphughes additional questions:
- How do you close invocation in Lambda? Is this normal async handler that simply resolves? Or do you resove via `callback`?
- Are those functions running close to timeout (do you also observe occasional timeout errors?)

Generally, this error signals that the previous invocation ended in some not natural manner, yet the same ongoing instance was used to handle the following invocation.

**Comment by simonphughes** [comment]
We do have the occasional timeout on functions, but these erroring as per screenshot below are well within the time available.
![image](https://user-images.githubusercontent.com/19175683/206748184-67448100-44e8-4671-b8f4-dc2a6ae1951e.png)

Functions are all normal async handlers defined as below
export const handleupdatemessage: ValidatedEventAPIGatewayProxyEvent<typeof schema> = async (event): Promise<APIGatewayProxyResult> => {

which then end with a 
return OKReponse();

where OKResponse is defined thus. 
export const OKResponse = () => {
  return {
    statusCode: 200,
    body: null,
    headers: null
  }
}

**Comment by medikoo** [comment]
@simonphughes thanks for more details.

I believe I know what’s going on. It’s a corner case, when invocation starts with some work (that was scheduled in previous invocation) before having handler run by the AWS. This signals likely processing flow error in lambda, still our extension should not break it. I'll work out a fix for it next week.

**Comment by simonphughes** [comment]
Great, thanks, please let me know when you have resolved. appreciate the quick replies on this thread.

**Comment by medikoo** [comment]
@simonphughes we've fixed it. It'll be released in production channel on Thursday.

Again, great thanks for reporting it!
